# Generated by Django 5.2.12 on 2026-03-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_reportingyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('source', models.CharField(choices=[('classroom', 'Classroom'), ('office', 'Office'), ('event', 'Event'), ('other', 'Other')], default='classroom', max_length=20)),
                ('waste_category', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('treatment_method', models.CharField(choices=[('recycled', 'Recycled'), ('composted', 'Composted'), ('landfilled', 'Landfilled'), ('incinerated', 'Incinerated'), ('co_processed', 'Co-processed')], max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emission_factor_used', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('co2e_kg', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('water_saved_litres', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('trees_equivalent', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporting_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_entries', to='schools.reportingyear')),
            ],
            options={
                'verbose_name': 'Waste Entry',
                'verbose_name_plural': 'Waste Entries',
                'db_table': 'waste_entries',
                'ordering': ['-entry_date'],
            },
        ),
    ]
