# Generated by Django 5.2.12 on 2026-04-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the waste entry', null=True),
        ),
    ]
