# Generated by Django 5.2.12 on 2026-04-16 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler_management', '0003_alter_recycler_vendor_type'),
        ('schools', '0004_school_short_name'),
        ('waste_management', '0003_wasteentry_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField(auto_now_add=True)),
                ('scheduled_pickup', models.DateField(blank=True, null=True)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('collected', 'Collected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycler_management.recycler')),
            ],
            options={
                'db_table': 'waste_dispatches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='waste_management.wastedispatch')),
                ('waste_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_management.wasteentry')),
            ],
            options={
                'db_table': 'waste_dispatch_items',
            },
        ),
    ]
