# Generated by Django 5.2.12 on 2026-04-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0004_wastedispatch_wastedispatchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteentry',
            name='remaining_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
