# Generated by Django 5.2.12 on 2026-03-28 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler_management', '0001_initial'),
        ('schools', '0002_reportingyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycler',
            name='certificates_issued',
            field=models.IntegerField(default=0, help_text='Number of recycling certificates issued'),
        ),
        migrations.AddField(
            model_name='recycler',
            name='certifications',
            field=models.TextField(blank=True, help_text='ISO, environmental certifications', null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary contact person name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST registration number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum pickup quantity in kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='recycler',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about vendor', null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='pickup_schedule',
            field=models.CharField(blank=True, help_text='Pickup days: Monday, Wednesday, Friday', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='processing_capacity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily processing capacity in kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='recycler',
            name='recycling_efficiency',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recycling efficiency percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='recycler',
            name='service_cities',
            field=models.TextField(blank=True, help_text='Cities where vendor provides service (comma separated)', null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='total_collected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total waste collected in kg', max_digits=12),
        ),
        migrations.AddField(
            model_name='recycler',
            name='total_processed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total waste processed in kg', max_digits=12),
        ),
        migrations.AddField(
            model_name='recycler',
            name='vendor_type',
            field=models.CharField(choices=[('collection', 'Collection Vendor'), ('recycling', 'Recycling Vendor'), ('disposal', 'Disposal Vendor'), ('composting', 'Composting Vendor'), ('e_waste', 'E-waste Vendor')], default='recycling', help_text='Type of vendor services', max_length=20),
        ),
        migrations.AddField(
            model_name='recyclermaterial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this material is currently accepted'),
        ),
        migrations.AddField(
            model_name='recyclermaterial',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price offered per kg (if applicable)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recycler',
            name='address',
            field=models.TextField(help_text='Full address'),
        ),
        migrations.AlterField(
            model_name='recycler',
            name='recycler_name',
            field=models.CharField(help_text='Vendor/Recycler company name', max_length=255),
        ),
        migrations.AlterField(
            model_name='recycler',
            name='trust_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Trust score based on performance (0-100)', max_digits=5),
        ),
        migrations.CreateModel(
            name='VendorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start', models.DateField(help_text='Contract start date')),
                ('contract_end', models.DateField(blank=True, help_text='Contract end date (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='recycler_management.material')),
                ('reporting_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='schools.reportingyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='schools.school')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to='recycler_management.recycler')),
            ],
            options={
                'db_table': 'vendor_assignments',
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'school', 'reporting_year', 'material')},
            },
        ),
    ]
