# Generated by Django 5.2.12 on 2026-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler_management', '0002_recycler_certificates_issued_recycler_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycler',
            name='vendor_type',
            field=models.CharField(choices=[('collection', 'Collection Vendor'), ('recycling', 'Recycling Vendor'), ('disposal', 'Disposal Vendor'), ('composting', 'Composting Vendor'), ('e_waste', 'E-waste Vendor')], default='recycling', help_text='Type of vendor services', max_length=100),
        ),
    ]
