# Generated by Django 5.2.12 on 2026-03-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
