# Generated by Django 5.2.12 on 2026-04-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_set_password_token_user_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
