# Generated by Django 5.2.12 on 2026-03-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_years', to='schools.school')),
            ],
            options={
                'db_table': 'reporting_years',
                'ordering': ['-created_at'],
                'unique_together': {('school', 'year')},
            },
        ),
    ]
