# Generated by Django 5.2.12 on 2026-04-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
