# Generated by Django 5.2.12 on 2026-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_category', models.CharField(max_length=100)),
                ('treatment_method', models.CharField(max_length=50)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('water_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trees_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
                'db_table': 'emission_factors',
            },
        ),
    ]
