# Generated by Django 5.2.12 on 2026-03-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('co2_effect', models.CharField(choices=[('negative', 'Negative (Avoids CO₂)'), ('positive', 'Positive (Generates CO₂)'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('water_effect', models.CharField(choices=[('positive', 'Positive (Saves Water)'), ('negative', 'Negative (Consumes Water)'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Treatment Method',
                'verbose_name_plural': 'Treatment Methods',
                'db_table': 'esg_treatment_methods',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waste Category',
                'verbose_name_plural': 'Waste Categories',
                'db_table': 'esg_waste_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WasteSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tree_type', models.CharField(blank=True, choices=[('pine', 'Pine (Softwood)'), ('spruce', 'Spruce (Softwood)'), ('eucalyptus', 'Eucalyptus (Hardwood)'), ('acacia', 'Acacia (Hardwood)'), ('mixed', 'Mixed (Softwood + Hardwood)'), ('bamboo', 'Bamboo (Grass)'), ('hemp', 'Hemp (Crop)'), ('bagasse', 'Bagasse (Agricultural Waste)'), ('cotton', 'Cotton (Textile Waste)'), ('none', 'None (Recycled/Alternative)'), ('other', 'Other')], max_length=50, null=True)),
                ('growth_rate_years', models.CharField(blank=True, help_text="e.g., '20-30 years'", max_length=50, null=True)),
                ('co2_absorption', models.DecimalField(blank=True, decimal_places=2, help_text='kg CO₂ per tree per year', max_digits=10, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='esg_tracking.wastecategory')),
            ],
            options={
                'verbose_name': 'Waste Sub-Category',
                'verbose_name_plural': 'Waste Sub-Categories',
                'db_table': 'esg_waste_sub_categories',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ESGFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_factor', models.DecimalField(decimal_places=6, help_text='t CO₂e per tonne (negative = avoided, positive = generated)', max_digits=10)),
                ('water_factor', models.DecimalField(blank=True, decimal_places=2, help_text='Litres saved per tonne', max_digits=12, null=True)),
                ('trees_factor', models.DecimalField(blank=True, decimal_places=4, help_text='Trees saved per tonne (only for paper category)', max_digits=10, null=True)),
                ('energy_factor', models.DecimalField(blank=True, decimal_places=2, help_text='kWh saved per tonne', max_digits=10, null=True)),
                ('source_standard', models.CharField(blank=True, help_text='e.g., IPCC 2019, GHG Protocol', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_edited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_factors', to='esg_tracking.treatmentmethod')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_factors', to='esg_tracking.wastesubcategory')),
            ],
            options={
                'verbose_name': 'ESG Factor',
                'verbose_name_plural': 'ESG Factors',
                'db_table': 'esg_factors',
                'ordering': ['sub_category__category__order', 'sub_category__order', 'treatment__order'],
                'unique_together': {('sub_category', 'treatment')},
            },
        ),
    ]
