# Generated by Django 5.2.12 on 2026-04-06 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_tracking', '0002_treatmentmethod_wastecategory_wastesubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecategory',
            name='default_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_categories', to='esg_tracking.wastesubcategory'),
        ),
        migrations.AddField(
            model_name='wastecategory',
            name='default_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_categories', to='esg_tracking.treatmentmethod'),
        ),
    ]
